### ISSUE TITLE
How I can reduce GPU memory usage

### ISSUE THREAD

**Issue by Qjizhi** [cogsys-tuebingen/mobilestereonet#10]
my device is 3080 16GB, but with the original code, I can only train with batch_size=1, otherwise, cuda out of memory.

I tried with Mixed Precision, and I can increase batch_size to 2, how can I train with large batch size without dropping accuracy.

**Comment by paritosh-101** [comment]
Works fine with the KITTI 2015 dataloader but when I try to pass images of my own (281x618) CUDA runs out of memory. I am running 4 GB GPU.
![cuda_mem](https://user-images.githubusercontent.com/9494125/144362597-dd931890-14f8-4bf7-9378-9414352608c9.png)

**Comment by samuel-woerz** [comment]
As mentioned in the mail, we used multiple GPUs to enable bigger batch sizes.
