### ISSUE TITLE
File names in file list don't seem to match file names in dataset(s)

### ISSUE THREAD

**Issue by schmidtp1** [cogsys-tuebingen/mobilestereonet#12]
e.g. https://github.com/cogsys-tuebingen/mobilestereonet/blob/main/filenames/ds_test.txt#L1 doesn't seem to match the filenames in DrivingStereo as in the dataset provided on the linked website: https://drivingstereo-dataset.github.io/, which, e.g., are in the form 2018-07-11-14-48-52_2018-07-11-15-45-53-241.jpg. also the folder structure seems to be different. it seems to be the same issue for SceneFlow.
is there any mismatch in the version of the dataset(s) or preprocessing required? in case, is the preprocessing described somewhere (maybe i missed it?).

**Comment by fshamsafar** [comment]
The training and test files are similar to the original datasets. We have just renamed them in order.
