### ISSUE TITLE
where to download the right scene flow dataset for pretraining? 

### ISSUE THREAD

**Issue by ynjiun** [cogsys-tuebingen/mobilestereonet#13]
could you point me to where to download the right dataset for SF pretraining? 

After follow [Sceneflow](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html) hyperlink, 
I downloaded Sceneflow disparity and frames_finalpass dataset.

But when I checked ./filenames/sceneflow_train.txt, the file path are different from dataset:

./filenames/sceneflow_train.txt: for example:
frames_finalpass/TRAIN/15mm_focallength/scene_backwards/slow/left/0224.png
frames_finalpass/TRAIN/A/0605/left/0015.png
frames_finalpass/TRAIN/B/0665/left/0006.png

in the downloaded dataset: for example:
frames_finalpass/15mm_focallength/scene_backwards/slow/left/0224.png
there is no TRAIN/, TRAIN/A/ or TRAIN/B directories.

Where is TRAIN/, TRAIN/A/, or TRAIN/B from? 
Is there a script that I can run to automatically download all the dataset needed and prepare them in the right directory hierarchy as specified in ./filenames/*.txt? Please advise.

Thank you very much for your help in advance.

**Comment by samuel-woerz** [comment]
Aside from the Scene Flow Driving Dataset, we also use Scene Flow FlyingThings3D and Scene Flow Monkaa. 
A, B and C are from FlyingThings3D. 
We dont have a script, but I have added instructions below and in the Readme.

---
**SceneFlow Dataset Preparation**

Download the finalpass images and the disparity data for SceneFlow FlyingThings3D, Driving and Monkaa.
For both, image and disparity data, move the directories in the TRAIN and TEST directories of the Driving and Monkaa Dataset (15mm_focallength/35mm_focallength for Driving,  funnyworld_x2 etc. for Monkaa) into the FlyingThings3D TRAIN and TEST directories, respectively.

It should look like this:

```
frames_finalpass
│
└───TEST
│   │
│   └───A
│   └───B
│   └───C
│   
│
└───TRAIN
│   │
│   └───15mm_focallength
│   └───35mm_focallength
│   └───A
│   └───a_rain_of_stones_x2
│   └─── ..
```
