### ISSUE TITLE
Thank you!  Working to get this running in DepthAI for Embedded Use-Case

### ISSUE THREAD

**Issue by Luxonis-Brandon** [cogsys-tuebingen/mobilestereonet#2]
Hi there,

I just wanted to reach out to say that this looks awesome!  We make a AI-capable stereo camera ecosystem called DepthAI (Github: https://github.com/luxonis/depthai-hardware) which actually is pretty well tuned to run MobileNetV1- and MobileNetV2- based networks.  

So we are SUPER excited to try to get this running in our ecosystem!

No real issue here - just wanted to say thanks - and that we'll be working to get this running in DepthAI, issue https://github.com/luxonis/depthai/issues/476.

-Brandon \\ OpenCV / Luxonis

**Comment by PINTO0309** [comment]
Once the author releases all the code and trained models, I will try to convert them to ONNX, OpenVINO, Myriad Blob, TensorFlow, TensorFlow Lite, EdgeTPU, CoreML, TensorFlow.js, and TF-TRT (TensorRT) models.

**Comment by Luxonis-Brandon** [comment]
Thanks.  Just now noticed it isn't all there yet.  Super excited for this to be released!

**Comment by fshamsafar** [comment]
> ecosystem
Hi Brandon,


My apologies for the late reply.

We are thrilled to hear our model is going to be deployed on a real hardware, which was the ultimate goal of this research!

DepthAI is indeed a cool platform for various ai-based vision tasks, and we are eagerly waiting to see it running MobileStereoNet for its depth perception. 

We will update the repo with more code/results very soon.


Faranak

**Comment by fshamsafar** [comment]
> Hi there,
> 
> I just wanted to reach out to say that this looks awesome! We make a AI-capable stereo camera ecosystem called DepthAI (Github: https://github.com/luxonis/depthai-hardware) which actually is pretty well tuned to run MobileNetV1- and MobileNetV2- based networks.
> 
> So we are SUPER excited to try to get this running in our ecosystem!
> 
> No real issue here - just wanted to say thanks - and that we'll be working to get this running in DepthAI, issue [luxonis/depthai#476](https://github.com/luxonis/depthai/issues/476).
> 
> -Brandon \ OpenCV / Luxonis

Hi Brandon,


My apologies for the late reply.

We are thrilled to hear our model is going to be deployed on a real hardware, which was the ultimate goal of this research!

DepthAI is indeed a cool platform for various ai-based vision tasks, and we are eagerly waiting to see it running MobileStereoNet for its depth perception. 

We will update the repo with more code/results very soon.


Faranak

**Comment by fshamsafar** [comment]
> Once the author releases all the code and trained models, I will try to convert them to ONNX, OpenVINO, Myriad Blob, TensorFlow, TensorFlow Lite, EdgeTPU, CoreML, TensorFlow.js, and TF-TRT (TensorRT) models.
> 
> I'll wait patiently.

Awesome! This helps to have more accelerated version of MobileStereoNet and see its potential for even being lighter.

**Comment by PINTO0309** [comment]
Two weeks ago, I have already finished preparing to convert the model. :+1:

**Comment by Qjizhi** [comment]
> Two weeks ago, I have already finished preparing to convert the model. +1

Could you please share your code link? Thanks!

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/150_MobileStereoNet
https://github.com/ibaiGorordo/ONNX-MobileStereoNet

**Comment by Qjizhi** [comment]
> https://github.com/PINTO0309/PINTO_model_zoo/tree/main/150_MobileStereoNet https://github.com/ibaiGorordo/ONNX-MobileStereoNet https://github.com/ibaiGorordo/TFLite-MobileStereoNet

Thanks! That helps!

**Comment by flyxuexi** [comment]
> > Once the author releases all the code and trained models, I will try to convert them to ONNX, OpenVINO, Myriad Blob, TensorFlow, TensorFlow Lite, EdgeTPU, CoreML, TensorFlow.js, and TF-TRT (TensorRT) models.
> > I'll wait patiently.
> 
> Awesome! This helps to have more accelerated version of MobileStereoNet and see its potential for even being lighter.

3D-mobilestereonet can not reach the test results of kitti2015，why？thanks。I used the MSNet3D_SF_KITTI2015.ckpt you provided.We submitted the parallax map to the kitti website, but the results were very different from those in the paper. In the paper, it is 1.75 3.87 2.10 1.61 3.50 1.92, but what I measured is 2.01 4.40 2.40 1.85 3.88 2.18, is it the wrong way for me to fine-tune, or is it for some other reason? Please help me.
