### ISSUE TITLE
Pretrained Netwrok

### ISSUE THREAD

**Issue by orram** [cogsys-tuebingen/mobilestereonet#23]
Hi,

Thank you for this project! Are there any trained weights you can share?

**Comment by orram** [comment]
Found it in the table

**Comment by flyxuexi** [comment]
> Found it in the table

3D-mobilestereonet can not reach the test results of kitti2015，why？thanks。I used the MSNet3D_SF_KITTI2015.ckpt you provided.We submitted the parallax map to the kitti website, but the results were very different from those in the paper. In the paper, it is 1.75 3.87 2.10 1.61 3.50 1.92, but what I measured is 2.01 4.40 2.40 1.85 3.88 2.18, is it the wrong way for me to fine-tune, or is it for some other reason? Please help me.
