### ISSUE TITLE
train the network

### ISSUE THREAD

**Issue by fengkai11** [cogsys-tuebingen/mobilestereonet#3]
Thank you for your great work. I want to see the details of the the extension from 2D to 3D convolution and find there is no model ! I noticed a record of detete, is there something wrong? waiting for the rest, thank you again.

**Comment by fshamsafar** [comment]
> Thank you for your great work. I want to see the details of the the extension from 2D to 3D convolution and find there is no model ! I noticed a record of detete, is there something wrong? waiting for the rest, thank you again.

Thank you for your interest in our work. We will soon update the repo with models, by which we have reported the results in the preprint :)
