### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by AminA193** [cogsys-tuebingen/mobilestereonet#5]
HI. I get out of memory error when executing train.py code. I reduced batch size but get same error. my GPU is Nvidia 1060 6GB.
the error is:
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 5.94 GiB total capacity; 4.78 GiB already allocated; 27.19 MiB free; 4.80 GiB reserved in total by PyTorch)

I appreciate any help to fix this error. thanks in advance.

update:
I could successfully train a model with batch size 1 but with batch size greater than 1 I get "out of memory error" which is discussed above.

**Comment by AminA193** [comment]
update:
I could successfully train a model with batch size 1 but with batch size greater than 1 I get "out of memory error" which is discussed in previous comment.

**Comment by blackHorz** [comment]
Yes if your hardware does not supports this then one cannot do anything. You can close the issue.

**Comment by fshamsafar** [comment]
@AminA193 
You need at least 1080 to run the 3D model.
Otherwise, you can use smaller training crops, but still the test would be a problem.
Or you can use smaller expansion factor in the two MobileNet-V2 of the first convolutions and pre-hourglass.
If that also does not work, you can replace them with simple convolutions.
Yet, all of these will lead to less accurate results.

**Comment by flyxuexi** [comment]
> @AminA193 You need at least 1080 to run the 3D model. Otherwise, you can use smaller training crops, but still the test would be a problem. Or you can use smaller expansion factor in the two MobileNet-V2 of the first convolutions and pre-hourglass. If that also does not work, you can replace them with simple convolutions. Yet, all of these will lead to less accurate results.

3D-mobilestereonet can not reach the test results of kitti2015，why？thanks。I used the MSNet3D_SF_KITTI2015.ckpt you provided.We submitted the parallax map to the kitti website, but the results were very different from those in the paper. In the paper, it is 1.75 3.87 2.10 1.61 3.50 1.92, but what I measured is 2.01 4.40 2.40 1.85 3.88 2.18, is it the wrong way for me to fine-tune, or is it for some other reason? Please help me.
