### ISSUE TITLE
Will there be a release of the pretrained model?

### ISSUE THREAD

**Issue by leaf0793** [cogsys-tuebingen/mobilestereonet#6]
Same

**Comment by Reichenbachian** [comment]
This would be very useful.

**Comment by blackHorz** [comment]
I have trained the model and have achieved the same results as mentioned in the repo. I would soon publish the weights.

**Comment by ppyht2** [comment]
+1 @blackHorz  looking forward to the weights

**Comment by jucic** [comment]
> I have trained the model and have achieved the same results as mentioned in the repo. I would soon publish the weights.

looking forward to the weights +1

**Comment by P-Chao** [comment]
I have trained mobilestereonet2d with kitti2015, 400 epoch, share the weight:
 https://pan.baidu.com/s/11RiZnBPgra2gEV3aRGTrkA              password: kurs
