### ISSUE TITLE
Why are there 3D conv. in the 2D model?

### ISSUE THREAD

**Issue by schmidtp1** [cogsys-tuebingen/mobilestereonet#7]
e.g. https://github.com/cogsys-tuebingen/mobilestereonet/blob/main/models/MSNet2D.py#L73

**Comment by fshamsafar** [comment]
@schmidtp1 
The 3D convolutions in the 2D model are used for the cost volume computation. We use the naming of 2D or 3D model following the 2D or 3D _encoder-decoder_.
