### ISSUE TITLE
Converting pytorch model to torchscript or ONNX format for inference in C++

### ISSUE THREAD

**Issue by nakul3112** [cogsys-tuebingen/mobilestereonet#9]
Hi @AdrianZw

  Are there any scripts or resources to convert the mobilestereonet to torchscript or ONNX format?  I want to use those formats for inference in C++. Any suggestions would be greatly appreciated.

Thanks.

**Comment by bartoszptak** [comment]
[Here](https://github.com/PUTvision/mobilestereonet) I prepared two scripts: `export_to_onnx.py` and `onnx_prediction.py`. I successfully use onnx model (2D and 3D) to predict labels, but it is so slow with `CPUExecutionProvider`. I also tried using [onnx-simplifier](https://github.com/daquexian/onnx-simplifier), but I do have not enough RAM.

I hope, scripts will be a good suggestion for you.

**Comment by nakul3112** [comment]
Hey @bartoszptak ,

   Thank you very much for assisting me  with this scripts. I will check and run them. However, as far as I know, we can also make predictions in C++, meaning a C++ code to do inference with ONNX model, right?

  Lastly, I would be glad if you could guide me in this very direction. That will be really appreciated. Thanks for your time and consideration in advance.

Regards,
Nakul Patel

**Comment by bartoszptak** [comment]
Propably, [Onnx runtime](https://onnxruntime.ai/)  works with both c++ and python, but I have used python only.

**Comment by nakul3112** [comment]
Ok, thanks. I will look into how to use it with c++

**Comment by Qjizhi** [comment]
> Propably, [Onnx runtime](https://onnxruntime.ai/) works with both c++ and python, but I have used python only.

I got GPU for 1.6s and CPU for 10s as inference speed, Do you think we can make it to 0.5s as reported by author?

**Comment by nakul3112** [comment]
hi @Qjizhi ,

   did you implement onnx-runtime in python or c++?

**Comment by Qjizhi** [comment]
> hi @Qjizhi ,
> 
> did you implement onnx-runtime in python or c++?

python, haven't tried c++ yet, it should be faster.

**Comment by nakul3112** [comment]
Hi @bartoszptak , I tried using your code export_to_onnx.py, but I get following error:
 File "/home/nakul.patel/anaconda3/envs/mobilestereonet/lib/python3.6/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/nakul.patel/anaconda3/envs/mobilestereonet/lib/python3.6/site-packages/torch/onnx/utils.py", line 656, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/nakul.patel/anaconda3/envs/mobilestereonet/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'new_zeros'

Do you know, what might be the reason? Is this some dependency issue?

**Comment by samuel-woerz** [comment]
> > Propably, [Onnx runtime](https://onnxruntime.ai/) works with both c++ and python, but I have used python only.
> 
> I got GPU for 1.6s and CPU for 10s as inference speed, Do you think we can make it to 0.5s as reported by author?

The numbers reported on the kitti benchmark are dummy numbers that we then forgot to update.
The pytorch inference times on a 1080Ti are around 1.5s for MSNet3D and 0.4s for MSNet2D.
We are sorry about any confusion caused by this.
